### ISSUE TITLE
[LangChain] make session, keyspace optional for Cassandra init

### ISSUE THREAD

**Issue by mukundha** [CassioML/cassio#110]
cassio.init() is really nice, but post that creating a vector store still requires passing session and keyspace with None values, can we make this optional?
for eg,
```
vstore = Cassandra(
    table_name='mytable,
    embedding=..,       
    session= None,
    keyspace= None 
)
```

**Comment by hemidactylus** [comment]
Thank you for raising this point. This is addressed for some time (so far in a fork of mine) and I need to find the time to polish the corresponding PR. Also this requires some negotiating with the LC folks since it is a backward-incompatible change (albeit small) for hypothetical folks using positional-arg init statements.
I will turn back to a string of PRs to langchain in the next 2 weeks or so, I think.
