### ISSUE TITLE
Add support for Semantic Kernel

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#71]
This is to support Microsoft Integration Efforts.

Semantic Kernel currently supports .NET clients and Java clients.

**Comment by xingh** [comment]
- Details
  - This is to support Microsoft Integration Efforts.
  - Semantic Kernel currently supports .NET clients and Java clients.
  - Semantic Kernel has a Python / C# version that interprets language agnostic semantic skills and native skills done in any language e.g. Java
  - Existing "Memory" connectors include Azure Cognitive Search, Chroma, DuckDB, Kusto, Pinecone, Postgres, QDrant, Redis, Sqlite, Weaviate

- Outcome
  - Creation of a Python Connector - both CQL and CQL Vector
    - semantic_kernel.connectors.memory.cassandra
  - Example use of memory connector in Python
  - Clarify how Java will be leveraged since right now it's used as a gRPC server used from within the C# SemKernel
  - LATER - Creation of a C# Connector - both CQL and CQL Vector
    - Microsoft.SemanticKernel.Connectors.Memory.Cassandra
  - LATER - Example use of memory connector in C#
- References
  - https://github.com/CassioML/cassio/issues/71
